name: Project Request 📜

description: Request for adding a new project to the repository.

labels:
  - up-for-grabs

body:
  - type: markdown
    attributes:
      value: |
        **Please ensure that all sections are filled out properly to help us evaluate the project request effectively.**

  - type: checkboxes
    id: terms
    attributes:
      label: "Important Points to Note"
      options:
        - label: "I agree to adhere to the project's [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md)."
          required: true
        - label: "I have reviewed and understood the project's [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md)."
          required: true
        - label: "I have checked the existing issues and can confirm that this is not a duplicate."
          required: true
        - label: "I have reviewed and understood the project's [Issue Creation Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/issues/108)."
          required: true

  - type: textarea
    id: project-description
    attributes:
      label: "Project Description"
      placeholder: "Provide a detailed description of the project, including its features and objectives."
    validations:
      required: true

  - type: input
    id: screenshots
    attributes:
      label: "Screenshots"
      placeholder: "Include relevant links or screenshots related to the project."
    validations:
      required: true

  - type: dropdown
    id: project-category
    attributes:
      label: "Project Category"
      description: "Select the appropriate category for the project."
      options:
        - "Angular JS"
        - "HTML/CSS"
        - "Next JS"
        - "Node JS"
        - "React JS"
        - "Typescript"
        - "HTML/CSS/JS"
        - "Vue JS"
    validations:
      required: true

  - type: input
    id: tech-stacks
    attributes:
      label: "Tech Stacks"
      description: "List the technologies used in the project (comma-separated and in lowercase)."
      placeholder: "e.g., react, node.js, express"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: "Priority"
      description: "How much time should be allocated to this issue?"
      options:
        - "Up to 2 days"
        - "Up to 5 days"
        - "Up to 1 week"
    validations:
      required: true

  - type: dropdown
    id: open-source-program
    attributes:
      label: "Open Source Program"
      description: "Which open-source program are you participating in?"
      options:
        - "GSSoC"
        - "GSSoC-Ext"
        - "SSOC"
        - "SWOC"
        - "JWOC"
        - "Hacktoberfest"
        - "IWOC"
        - "KWOC"
        - "24 Pull Requests"
        - "DWOC"
        - "VSOC"

  - type: dropdown
    id: on-work
    attributes:
      label: "Would you like to work on this issue?"
      options:
        - "Yes"
        - "No"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        **Difficulty labels (e.g., Easy/Beginner) will be applied once the PR is created.**
        **Do not raise a PR without being assigned to the issue.**
        > **NOTE:** This issue will automatically be unassigned if the PR is not raised within the given time frame.

        ### Happy Coding! 🎉
        All the best with your contribution! 🚀
